# Generated by Django 3.2.12 on 2022-03-02 13:07

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogWalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usr_img', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to='usrImgs/')),
                ('email', models.EmailField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('price', models.IntegerField()),
                ('usr_info', models.TextField()),
                ('avbl_from', models.DateField()),
                ('avbl_to', models.DateField()),
                ('avbl_morn', models.BooleanField()),
                ('avbl_aftn', models.BooleanField()),
                ('avbl_eve', models.BooleanField()),
                ('acpt_7k', models.BooleanField()),
                ('acpt_18k', models.BooleanField()),
                ('acpt_45k', models.BooleanField()),
                ('acpt_abv_45k', models.BooleanField()),
                ('acpt_pup', models.BooleanField()),
            ],
        ),
    ]
